AlmaResourceSharingAPI/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'AlmaResourceSharingAPI.views.home', name='home'),
    url(r'^process/complete$', 'AlmaResourceSharingAPI.views.process_complete', name='complete'),
    url(r'^process/(?P<request_type>(article|book))/$', 'AlmaResourceSharingAPI.views.process_resource_sharing_request_form', name='process'),
    # url(r'^AlmaResourceSharingAPI/', include('AlmaResourceSharingAPI.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

AlmaResourceSharingAPI/forms.py
from django import forms


BOOK_OR_ARTICLE_CHOICES = (
    ('book', 'Book'),
    ('article', 'Article'),
)

FORMAT_CHOICES = (
    ('PHYSICAL', 'Print'),
    ('DIGITAL', 'Digital'),
)


class ResourceSharingRequestForm(forms.Form):
    # Generic user fields
    library_card_number = forms.CharField(widget=forms.TextInput(attrs={'class':'input-xxlarge', 'placeHolder':'University card number'}))
    name = forms.CharField(widget=forms.TextInput(attrs={'class':'input-xxlarge', 'placeHolder': 'Name'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class':'input-xxlarge', 'placeHolder': 'Email address'}))

    # General bibliographic fields
    title = forms.CharField(widget=forms.TextInput(attrs={'class':'input-xxlarge', 'placeHolder': 'Title of article/book'}))
    author = forms.CharField(required=False,widget=forms.TextInput(attrs={'class':'input-xxlarge', 'placeHolder': 'Author name'}))
    place_of_publication = forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'input-xxlarge', 'placeHolder': 'Place of publication'}))
    year = forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'input-xxlarge', 'placeHolder': 'Year of publication'}))
    notes = forms.CharField(required=False,widget=forms.Textarea(attrs={'class':'input-xxlarge'}))
    pages = forms.CharField(required=False,widget=forms.TextInput(attrs={'class':'input-xxlarge', 'placeHolder': 'Pages'}))

    # Article specific fields
    journal_title = forms.CharField(required=False,widget=forms.TextInput(attrs={'class':'input-xxlarge', 'placeHolder': 'Title of journal'}))
    volume = forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'input-xxlarge', 'placeHolder': 'Volume'}))
    issue = forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'input-xxlarge', 'placeHolder': 'Issue number'}))
    issn = forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'input-xxlarge', 'placeHolder': 'ISSN'}))

    # Book specific fields
    publisher = forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'input-xxlarge', 'placeHolder': 'Publisher'}))
    edition = forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'input-xxlarge', 'placeHolder': 'Edition'}))
    isbn = forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'input-xxlarge', 'placeHolder': 'ISBN'}))
    chapter = forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'input-xxlarge', 'placeHolder': 'Chapter'}))
    classmark = forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'input-xxlarge', 'placeHolder': 'Classmark'}))

    # Request specific fields
    format = forms.ChoiceField(choices=FORMAT_CHOICES, widget=forms.Select(attrs={'class':'input-xxlarge'}))
    not_required_after = forms.CharField(widget=forms.TextInput(attrs={'class':'input-xxlarge'}))
    copyright_agreement = forms.BooleanField()


class BookOrArticleForm(forms.Form):
    book_or_article = forms.ChoiceField(choices=BOOK_OR_ARTICLE_CHOICES, widget=forms.Select(attrs={'class':'input-xxlarge'}))

AlmaResourceSharingAPI/views.py
from django.shortcuts import render, redirect
from AlmaResourceSharingAPI.forms import ResourceSharingRequestForm, BookOrArticleForm
from lxml import etree
from AlmaResourceSharingAPI.settings import API_address, API_password, API_username
from AlmaResourceSharingAPI.settings import AlertEmail_subject, AlertEmail_message_text, AlertEmail_message_html, AlertEmail_from
from AlmaResourceSharingAPI.settings import PRIMO_URL, PRIMO_DISPLAY_URL
import requests
from string import Template
from django.core.mail import EmailMultiAlternatives
import urllib



class ResourceSharingRequest:
    def __init__(self):
        pass

    def generate_payload(self):
        root = etree.Element("user_resource_sharing_request")

        for key, value in self.__dict__.items():

            if key == 'library_card_number' or key == 'name':
                continue

            element = etree.Element(key)
            element.text = value

            if key == 'format':
                element.set("desc", value)

            if key == 'citation_type':
                if value == 'BK':
                    element.set('desc', 'Book')
                else:
                    element.set('desc', 'Article')

            root.append(element)

        masud = etree.tostring(root)
        print etree.tostring(root)
        return etree.tostring(root)

    def primo_search(self):
        # Primo default name space
        DEFAULT_NS = 'http://www.exlibrisgroup.com/xsd/primo/primo_nm_bib'

        # We test for the exact title value
        query = 'title,exact,' + self.title

        # We will look for at most 10 results
        url = PRIMO_URL + '&query=' + query + '&indx=1&bulkSize=10'

        content = urllib.urlopen(url)
        xml = etree.parse(content)

        docset = xml.getroot().xpath('//sear:SEGMENTS/sear:JAGROOT/sear:RESULT/sear:DOCSET', namespaces={'sear': 'http://www.exlibrisgroup.com/xsd/jaguar/search', 'def': DEFAULT_NS})
        totalhits = docset[0].get("TOTALHITS");
        docs = xml.getroot().xpath('//sear:SEGMENTS/sear:JAGROOT/sear:RESULT/sear:DOCSET/sear:DOC/def:PrimoNMBib/def:record', namespaces={'sear': 'http://www.exlibrisgroup.com/xsd/jaguar/search', 'def': DEFAULT_NS})

        list_data = []
        for doc in docs:
            data = {}
            data['totalhits'] = totalhits
            data['record_id'] = doc.findtext('{%s}control/{%s}recordid' %(DEFAULT_NS, DEFAULT_NS))
            data['title'] = doc.findtext('{%s}display/{%s}title' %(DEFAULT_NS, DEFAULT_NS))
            data['creationdate'] = doc.findtext('{%s}display/{%s}creationdate' %(DEFAULT_NS, DEFAULT_NS))
            data['publisher'] = doc.findtext('{%s}display/{%s}publisher' %(DEFAULT_NS, DEFAULT_NS))
            creator = doc.findtext('{%s}display/{%s}creator' %(DEFAULT_NS, DEFAULT_NS))
            contributor = doc.findtext('{%s}display/{%s}contributor' %(DEFAULT_NS, DEFAULT_NS))
            if creator:
                data['author'] = creator
            else:
                data['author'] = 'No author specified'
            data['type'] = doc.findtext('{%s}display/{%s}type' %(DEFAULT_NS, DEFAULT_NS))
            s = Template(PRIMO_DISPLAY_URL)
            link = s.substitute(record_id=data['record_id'])
            data['display_link'] = link
            list_data.append(data)

        return list_data


'''
    method: home
    author: Masud Khokhar
    parameters: request
    returns: article form or book form
    acceptable request methods: GET or POST
'''


def home(request):
    # If the request method is GET, then show the basic form for selection of Book or Article
    if request.method == 'GET':
        form = BookOrArticleForm()
        # Define the context for the render operation. This is additional values you want to pass to the template.
        context = {'BookOrArticleForm': form}
        return render(request, 'home.html', context)
    # If the request method is POST, then the user has selected either book or article. Make a decision on that choice.
    else:
        form = BookOrArticleForm(request.POST)
        if form.is_valid:
            # Grab the value from the request for the user's choice
            request_type = request.POST.get('book_or_article')

            return redirect('process', request_type=request_type)


'''
    method: process_resource_sharing_request_form
    author: Masud Khokhar
    parameters: request, request_type (article or book)
    returns:
    acceptable request methods: GET or POST
'''


def process_resource_sharing_request_form(request, request_type):
    if request.method == 'GET':
        form = ResourceSharingRequestForm()
        context = {'ResourceSharingRequestForm': form, 'request_type': request_type}
        return render(request, 'resource_sharing_request_form.html', context)
    else:
        form = ResourceSharingRequestForm(request.POST)

        if form.is_valid():
            # Create a new instance of ResourceSharingRequest
            resource_sharing_request = ResourceSharingRequest()

            # Assign values from the submitted form to the above created instance of ResourceSharingRequest
            # We will assign all values here regardless of whether it would be an article form or a book form

            # Generic user fields
            resource_sharing_request.library_card_number = form.cleaned_data['library_card_number']

            resource_sharing_request.name = form.cleaned_data['name']

            resource_sharing_request.text_email = form.cleaned_data['email']

            # General bibliographic fields
            resource_sharing_request.title = form.cleaned_data['title']

            resource_sharing_request.author = form.cleaned_data['author']

            resource_sharing_request.place_of_publication = form.cleaned_data['place_of_publication']

            resource_sharing_request.year = form.cleaned_data['year']

            resource_sharing_request.note = form.cleaned_data['notes']

            resource_sharing_request.pages = form.cleaned_data['pages']

            # Article specific fields
            resource_sharing_request.journal_title = form.cleaned_data['journal_title']

            resource_sharing_request.volume = form.cleaned_data['volume']

            resource_sharing_request.issue = form.cleaned_data['issue']

            resource_sharing_request.issn = form.cleaned_data['issn']

            # Book specific fields
            resource_sharing_request.publisher = form.cleaned_data['publisher']

            resource_sharing_request.edition = form.cleaned_data['edition']

            resource_sharing_request.isbn = form.cleaned_data['isbn']

            resource_sharing_request.chapter = form.cleaned_data['chapter']

            resource_sharing_request.call_number = form.cleaned_data['classmark']

            # Request specific fields
            resource_sharing_request.format = form.cleaned_data['format']

            resource_sharing_request.last_interest_date = form.cleaned_data['not_required_after']

            if form.cleaned_data['copyright_agreement']:
                resource_sharing_request.agree_to_copyright_terms = 'true'
            else:
                resource_sharing_request.agree_to_copyright_terms = 'false'

            if request_type == 'article':
                resource_sharing_request.citation_type = 'CR'
            else:
                resource_sharing_request.citation_type = 'BK'

            resource_sharing_request.use_alternative_address = 'true'

            resource_sharing_request.pickup_location = 'LANUL'

            payload = resource_sharing_request.generate_payload()

            # Definitely worth checking for this item in Primo and Primo Central
            primo_results = resource_sharing_request.primo_search()

            if primo_results:
                context = {'primo_results': primo_results, 'payload': payload}
                return render(request, 'exists.html', context)

            # Grab the logged in user name
            requesting_user = request.META.get('REMOTE_USER')

            # Place the API call to Alma
            response = place_API_call(payload, requesting_user, 'false')

            # Create an XML object from the API response for easy parsing
            response_xml = etree.fromstring(response)
            print response

            # Set the request ID to False and then check if there is one coming back from Alma
            request_id = False
            request_id = response_xml.findtext("request_id")

            # If a request ID has come back, then the request has been successfully placed
            if request_id:
                return render(request, 'success.html')
            # Otherwise, something has gone wrong, parse for error code and show the user a generic error page.
            else:
                alert_staff(resource_sharing_request.__dict__)
                return render(request, 'error.html')

        context = {'ResourceSharingRequestForm': form, 'request_type': request_type}
        return render(request, 'resource_sharing_request_form.html', context)


def process_complete(request):
    if request.method == 'GET':
        return redirect('home')
    if request.method == 'POST':

        payload = request.POST.get('payload')
        # Grab the logged in user name
        requesting_user = request.META.get('REMOTE_USER')

        # Place the API call to Alma
        response = place_API_call(payload, requesting_user, 'true')

        # Create an XML object from the API response for easy parsing
        response_xml = etree.fromstring(response)
        print response

        # Set the request ID to False and then check if there is one coming back from Alma
        request_id = False
        request_id = response_xml.findtext("request_id")

        # If a request ID has come back, then the request has been successfully placed
        if request_id:
            return render(request, 'success.html')

AlmaResourceSharingAPI/templates/book.html
{% extends 'base.html' %}

{% block message %}
    <h1>IDS request - Book</h1>
    <hr>
{% endblock %}

{% block form %}

    <form class="form-horizontal" action="/book" method="POST">{% csrf_token %}



        <div class="left-side-form">
            <h3>Your details</h3>
            <hr>

            {% if BookForm.libraryCardNumber.errors %}
                <div class="control-group error">
            {% else %}
                <div class="control-group">
            {% endif %}

                <label class="control-label" for="id_libraryCardNumber">
                    <span class="help-inline" style="color:red;">*</span> Library card number:
                </label>
                <div class="controls">
                    {{ BookForm.libraryCardNumber }}
                </div>
            </div>

            {% if BookForm.name.errors %}
                <div class="control-group error">
            {% else %}
                <div class="control-group">
            {% endif %}

                <label class="control-label" for="id_name">
                    <span class="help-inline" style="color:red;">*</span> Name:
                </label>
                <div class="controls">
                    {{ BookForm.name }}
                </div>
            </div>

            {% if BookForm.email.errors %}
                <div class="control-group error">
            {% else %}
                <div class="control-group">
            {% endif %}

                <label class="control-label" for="id_email">
                    <span class="help-inline" style="color:red;">*</span> Email address:
                </label>
                <div class="controls">
                    {{ BookForm.email }}
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="id_notes">Additional notes:</label>
                <div class="controls">
                    {{ BookForm.notes }}
                </div>
            </div>


        </div>

        <div class="right-side-form">
            <h3>Bibliographic Details</h3>
            <hr>

            {% if BookForm.title.errors %}
                <div class="control-group error">
            {% else %}
                <div class="control-group">
            {% endif %}

                <label class="control-label" for="id_title">
                    <span class="help-inline" style="color:red;">*</span> Title:
                </label>
                <div class="controls">
                    {{ BookForm.title }}
                </div>
            </div>


            <div class="control-group">
                <label class="control-label" for="id_author">Author:</label>
                <div class="controls">
                    {{ BookForm.author }}
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="id_publisher">Publisher:</label>
                <div class="controls">
                    {{ BookForm.publisher }}
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="id_year">Year:</label>
                <div class="controls">
                    {{ BookForm.year }}
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="id_edition">Edition:</label>
                <div class="controls">
                    {{ BookForm.edition }}
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="id_isbn">ISBN:</label>
                <div class="controls">
                    {{ BookForm.isbn }}
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="id_place_of_publication">Place of publication:</label>
                <div class="controls">
                    {{ BookForm.place_of_publication }}
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="id_classmark">Classmark:</label>
                <div class="controls">
                    {{ BookForm.classmark }}
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="id_chapter">Chapter:</label>
                <div class="controls">
                    {{ BookForm.chapter }}
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="id_pages">Pages:</label>
                <div class="controls">
                    {{ BookForm.pages }}
                </div>
            </div>


        </div>

    <div style="clear: both;"></div>
    <hr>

    <div class="left-side-form">

        {% if BookForm.not_required_after.errors %}


        <div class="control-group error">
        {% else %}
            <div class="control-group">
        {% endif %}

            <label class="control-label" for="id_not_required_after">
                <span class="help-inline" style="color:red;">*</span> Not required after:
            </label>
            <div class="controls">
                <div class="input-append date">
                    {{ BookForm.not_required_after }}
                    <span class="add-on"><i class="icon-calendar"></i></span>
                </div>

            </div>
        </div>

        {% if BookForm.copyright_agreement.errors %}
            <div class="control-group error">
        {% else %}
            <div class="control-group">
        {% endif %}

            <label class="control-label" for="id_copyright_agreement">
                <span class="help-inline" style="color:red;">*</span> Copyright agreement:
            </label>
            <div class="controls">
                <label class="checkbox">
                    {{ BookForm.copyright_agreement }} I have read and agree with this copyright declaration
                </label>
            </div>
        </div>
    </div>

    <div class="right-side-form">
        <div class="control-group">
            <input type="submit" class="btn btn-primary btn-large" value="Submit" />
        </div>
    </div>





    </form>

{% endblock %}

AlmaResourceSharingAPI/templates/error.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-narrow">
        <h2>Sorry but we are not able to place an IDS request for you at this time.</h2>
        <hr>
        <h4>This might be an issue with the system or with the request information you have provided. Please make sure that all data is correct and try again in a few minutes time.</h4>
        <h4>If the issue persists, please contact us at: library.ids@lancaster.ac.uk</h4>

        <h4>Thank you.</h4>
    </div>
{% endblock %}

AlmaResourceSharingAPI/templates/home.html
{% extends 'base.html' %}

{% block form %}

    <form class="form-horizontal form-inline" action="" method="POST">{% csrf_token %}
        <div class="middle-form">
            <div class="control-group">
                <label class="control-label" for="id_book_or_article" id="request_type_label">
                    <span class="help-inline" style="color:red;">*</span> Request type:
                </label>
                <div class="controls">
                    {{ BookOrArticleForm.book_or_article }}
                    &nbsp;
                <input type="submit" class="btn btn-primary btn-large" value="Submit" />
                </div>
            </div>
        </div>
    </form>

{% endblock %}

AlmaResourceSharingAPI/templates/resource_sharing_request_form.html
{% extends 'base.html' %}

{% block message %}
    {% if request_type == 'article' %}
        <h1>IDS request - Article</h1>
    {% else %}
        <h1>IDS request - Book</h1>
    {% endif %}
    <hr>
{% endblock %}

{% block form %}

    <form class="form-horizontal" action="" method="POST">{% csrf_token %}



        <div class="left-side-form">
            <h3>Your details</h3>
            <hr>

            {% if ResourceSharingRequestForm.library_card_number.errors %}
                <div class="control-group error">
            {% else %}
                <div class="control-group">
            {% endif %}

                <label class="control-label" for="id_library_card_number">
                    <span class="help-inline" style="color:red;">*</span> University card no.:
                </label>
                <div class="controls">
                    {{ ResourceSharingRequestForm.library_card_number }}
                </div>
            </div>

            {% if ResourceSharingRequestForm.name.errors %}
                <div class="control-group error">
            {% else %}
                <div class="control-group">
            {% endif %}

                <label class="control-label" for="id_name">
                    <span class="help-inline" style="color:red;">*</span> Name:
                </label>
                <div class="controls">
                    {{ ResourceSharingRequestForm.name }}
                </div>
            </div>

            {% if ResourceSharingRequestForm.email.errors %}
                <div class="control-group error">
            {% else %}
                <div class="control-group">
            {% endif %}

                <label class="control-label" for="id_email">
                    <span class="help-inline" style="color:red;">*</span> Email address:
                </label>
                <div class="controls">
                    {{ ResourceSharingRequestForm.email }}
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="id_notes">Request notes:</label>
                <div class="controls">
                    {{ ResourceSharingRequestForm.notes }}
                </div>
            </div>

            {% if ResourceSharingRequestForm.not_required_after.errors %}
                <div class="control-group error">
            {% else %}
                <div class="control-group">
            {% endif %}

                <label class="control-label" for="id_not_required_after">
                    <span class="help-inline" style="color:red;">*</span> Not required after:
                </label>
                <div class="controls">
                    <div class="input-append date">
                        {{ ResourceSharingRequestForm.not_required_after }}
                        <span class="add-on"><i class="icon-calendar"></i></span>
                    </div>

                </div>
            </div>

            {% if ResourceSharingRequestForm.format.errors %}
                <div class="control-group error">
            {% else %}
                <div class="control-group">
            {% endif %}
                    <label class="control-label" for="id_format">
                        <span class="help-inline" style="color:red;">*</span> Format:
                    </label>
                    <div class="controls">
                        {{ ResourceSharingRequestForm.format }}
                    </div>
                </div>

        </div>

        <div class="right-side-form">
            {% if request_type == 'article' %}
                <h3>Article details</h3>
            {% else %}
                <h3>Book Details</h3>
            {% endif %}
            <hr>

            {% if ResourceSharingRequestForm.title.errors %}
                <div class="control-group error">
            {% else %}
                <div class="control-group">
            {% endif %}

                <label class="control-label" for="id_title">
                    <span class="help-inline" style="color:red;">*</span> Title:
                </label>
                <div class="controls">
                    {{ ResourceSharingRequestForm.title }}
                </div>
            </div>

            {% if request_type == 'article' %}
                <div class="control-group">
                    <label class="control-label" for="id_journal_title">Journal title:</label>
                    <div class="controls">
                        {{ ResourceSharingRequestForm.journal_title }}
                    </div>
                </div>
            {% endif %}

            <div class="control-group">
                <label class="control-label" for="id_author">Author:</label>
                <div class="controls">
                    {{ ResourceSharingRequestForm.author }}
                </div>
            </div>

            {% if request_type == 'article' %}
                <div class="control-group">
                    <label class="control-label" for="id_volume">Volume:</label>
                    <div class="controls">
                        {{ ResourceSharingRequestForm.volume }}
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label" for="id_issue">Issue:</label>
                    <div class="controls">
                        {{ ResourceSharingRequestForm.issue }}
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label" for="id_issn">ISSN:</label>
                    <div class="controls">
                        {{ ResourceSharingRequestForm.issn }}
                    </div>
                </div>
            {% endif %}

            {% if request_type == 'book' %}
                <div class="control-group">
                    <label class="control-label" for="id_publisher">Publisher:</label>
                    <div class="controls">
                        {{ ResourceSharingRequestForm.publisher }}
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label" for="id_place_of_publication">Place of publication:</label>
                    <div class="controls">
                        {{ ResourceSharingRequestForm.place_of_publication }}
                    </div>
                </div>

	      {% endif %}

                <div class="control-group">
                    <label class="control-label" for="id_year">Year:</label>
                    <div class="controls">
                        {{ ResourceSharingRequestForm.year }}
                    </div>
                </div>

            {% if request_type == 'book' %}
                <div class="control-group">
                    <label class="control-label" for="id_edition">Edition:</label>
                    <div class="controls">
                        {{ ResourceSharingRequestForm.edition }}
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label" for="id_isbn">ISBN:</label>
                    <div class="controls">
                        {{ ResourceSharingRequestForm.isbn }}
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label" for="id_classmark">Classmark:</label>
                    <div class="controls">
                        {{ ResourceSharingRequestForm.classmark }}
                    </div>
                </div>

                <h4>Part details (if you require a copy of a part of the book)</h4>
                <hr>
                <div class="control-group">
                    <label class="control-label" for="id_chapter">Chapter:</label>
                    <div class="controls">
                        {{ ResourceSharingRequestForm.chapter }}
                    </div>
                </div>
            {% endif %}

            <div class="control-group">
                <label class="control-label" for="id_pages">Pages:</label>
                <div class="controls">
                    {{ ResourceSharingRequestForm.pages }}
                </div>
            </div>


        </div>

    <div style="clear: both;"></div>
    <hr>

    <div class="left-side-form">


        {% if ResourceSharingRequestForm.copyright_agreement.errors %}
            <div class="control-group error">
        {% else %}
            <div class="control-group">
        {% endif %}

            <label class="control-label" for="id_copyright_agreement">
                <span class="help-inline" style="color:red;">*</span> Copyright agreement:
            </label>
            <div class="controls">
                <label class="checkbox">
                    {{ ResourceSharingRequestForm.copyright_agreement }} I have read and agree with this copyright declaration
                </label>
            </div>
        </div>
    </div>

    <div class="right-side-form">
        <div class="control-group">
            <input type="submit" class="btn btn-primary btn-large" value="Submit" />
        </div>
    </div>


    </form>

{% endblock %}

AlmaResourceSharingAPI/templates/success.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-narrow">
        <h1>Thank you</h1>
        <h2>Your request has been successfully placed.</h2>

        <p>For your reference, we have placed a request for you and a confirmation email has been sent to you.</p>
        <p>If your request needs to be dealt with urgently and you have not added an urgent note to your request, please reply to that email and mention the urgency of the request.</p>
        <p>Thank you.</p>
    </div>
{% endblock %}